/*
 * generated by Xtext 2.10.0
 */
package se.chalmers.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TurtleBotMissionDSLProposalProvider extends AbstractTurtleBotMissionDSLProposalProvider {
}
