/*
 * generated by Xtext 2.10.0
 */
package se.chalmers


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TurtleBotMissionDSLStandaloneSetup extends TurtleBotMissionDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TurtleBotMissionDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
