/**
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot;

import se.jam.turtlebot.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
