/*
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import se.jam.turtlebot.ui.internal.TurtlebotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TurtlebotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TurtlebotActivator.getInstance().getInjector(TurtlebotActivator.SE_JAM_TURTLEBOT_MYDSL);
	}
	
}
