/*
 * generated by Xtext 2.10.0
 */
package se.chalmers.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTurtleBotMissionDSLScopeProvider extends DelegatingScopeProvider {
}
