/**
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.ui.contentassist;

import se.jam.turtlebot.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
