/*
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class TurtleBotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.TurtleBot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTurtleBotKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAreaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cAreaAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cAreaAreaParserRuleCall_3_2_0 = (RuleCall)cAreaAssignment_3_2.eContents().get(0);
		private final Keyword cWaypointTypesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWaypointtypesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cWaypointtypesWaypointTypeParserRuleCall_7_0 = (RuleCall)cWaypointtypesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cWaypointtypesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cWaypointtypesWaypointTypeParserRuleCall_8_1_0 = (RuleCall)cWaypointtypesAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cWaypointsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cEqualsSignKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cWaypointsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cWaypointsWayPointParserRuleCall_13_0 = (RuleCall)cWaypointsAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cCommaKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cWaypointsAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cWaypointsWayPointParserRuleCall_14_1_0 = (RuleCall)cWaypointsAssignment_14_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cBotStartsAtKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cEqualsSignKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cBot_startAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final CrossReference cBot_startWayPointCrossReference_18_0 = (CrossReference)cBot_startAssignment_18.eContents().get(0);
		private final RuleCall cBot_startWayPointEStringParserRuleCall_18_0_1 = (RuleCall)cBot_startWayPointCrossReference_18_0.eContents().get(1);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cMissionsKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Keyword cEqualsSignKeyword_19_1 = (Keyword)cGroup_19.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_19_2 = (Keyword)cGroup_19.eContents().get(2);
		private final Assignment cMissionsAssignment_19_3 = (Assignment)cGroup_19.eContents().get(3);
		private final RuleCall cMissionsMissionParserRuleCall_19_3_0 = (RuleCall)cMissionsAssignment_19_3.eContents().get(0);
		private final Group cGroup_19_4 = (Group)cGroup_19.eContents().get(4);
		private final Keyword cCommaKeyword_19_4_0 = (Keyword)cGroup_19_4.eContents().get(0);
		private final Assignment cMissionsAssignment_19_4_1 = (Assignment)cGroup_19_4.eContents().get(1);
		private final RuleCall cMissionsMissionParserRuleCall_19_4_1_0 = (RuleCall)cMissionsAssignment_19_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19_5 = (Keyword)cGroup_19.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//TurtleBot:
		//	'TurtleBot'
		//	name=EString
		//	'{' ('area' '=' area=Area)? 'waypoint types' '=' '{' waypointtypes+=WaypointType ("," waypointtypes+=WaypointType)*
		//	'}'
		//	'waypoints' '=' '{' waypoints+=WayPoint ("," waypoints+=WayPoint)* '}'
		//	'bot starts at' '=' bot_start=[WayPoint|EString] ('missions' '=' '{' missions+=Mission ("," missions+=Mission)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TurtleBot' name=EString '{' ('area' '=' area=Area)? 'waypoint types' '=' '{' waypointtypes+=WaypointType (","
		//waypointtypes+=WaypointType)* '}' 'waypoints' '=' '{' waypoints+=WayPoint ("," waypoints+=WayPoint)* '}'
		//'bot starts at' '=' bot_start=[WayPoint|EString] ('missions' '=' '{' missions+=Mission ("," missions+=Mission)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'TurtleBot'
		public Keyword getTurtleBotKeyword_0() { return cTurtleBotKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('area' '=' area=Area)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'area'
		public Keyword getAreaKeyword_3_0() { return cAreaKeyword_3_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_1() { return cEqualsSignKeyword_3_1; }
		
		//area=Area
		public Assignment getAreaAssignment_3_2() { return cAreaAssignment_3_2; }
		
		//Area
		public RuleCall getAreaAreaParserRuleCall_3_2_0() { return cAreaAreaParserRuleCall_3_2_0; }
		
		//'waypoint types'
		public Keyword getWaypointTypesKeyword_4() { return cWaypointTypesKeyword_4; }
		
		//'='
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//waypointtypes+=WaypointType
		public Assignment getWaypointtypesAssignment_7() { return cWaypointtypesAssignment_7; }
		
		//WaypointType
		public RuleCall getWaypointtypesWaypointTypeParserRuleCall_7_0() { return cWaypointtypesWaypointTypeParserRuleCall_7_0; }
		
		//("," waypointtypes+=WaypointType)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//waypointtypes+=WaypointType
		public Assignment getWaypointtypesAssignment_8_1() { return cWaypointtypesAssignment_8_1; }
		
		//WaypointType
		public RuleCall getWaypointtypesWaypointTypeParserRuleCall_8_1_0() { return cWaypointtypesWaypointTypeParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'waypoints'
		public Keyword getWaypointsKeyword_10() { return cWaypointsKeyword_10; }
		
		//'='
		public Keyword getEqualsSignKeyword_11() { return cEqualsSignKeyword_11; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12() { return cLeftCurlyBracketKeyword_12; }
		
		//waypoints+=WayPoint
		public Assignment getWaypointsAssignment_13() { return cWaypointsAssignment_13; }
		
		//WayPoint
		public RuleCall getWaypointsWayPointParserRuleCall_13_0() { return cWaypointsWayPointParserRuleCall_13_0; }
		
		//("," waypoints+=WayPoint)*
		public Group getGroup_14() { return cGroup_14; }
		
		//","
		public Keyword getCommaKeyword_14_0() { return cCommaKeyword_14_0; }
		
		//waypoints+=WayPoint
		public Assignment getWaypointsAssignment_14_1() { return cWaypointsAssignment_14_1; }
		
		//WayPoint
		public RuleCall getWaypointsWayPointParserRuleCall_14_1_0() { return cWaypointsWayPointParserRuleCall_14_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
		
		//'bot starts at'
		public Keyword getBotStartsAtKeyword_16() { return cBotStartsAtKeyword_16; }
		
		//'='
		public Keyword getEqualsSignKeyword_17() { return cEqualsSignKeyword_17; }
		
		//bot_start=[WayPoint|EString]
		public Assignment getBot_startAssignment_18() { return cBot_startAssignment_18; }
		
		//[WayPoint|EString]
		public CrossReference getBot_startWayPointCrossReference_18_0() { return cBot_startWayPointCrossReference_18_0; }
		
		//EString
		public RuleCall getBot_startWayPointEStringParserRuleCall_18_0_1() { return cBot_startWayPointEStringParserRuleCall_18_0_1; }
		
		//('missions' '=' '{' missions+=Mission ("," missions+=Mission)* '}')?
		public Group getGroup_19() { return cGroup_19; }
		
		//'missions'
		public Keyword getMissionsKeyword_19_0() { return cMissionsKeyword_19_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_19_1() { return cEqualsSignKeyword_19_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_19_2() { return cLeftCurlyBracketKeyword_19_2; }
		
		//missions+=Mission
		public Assignment getMissionsAssignment_19_3() { return cMissionsAssignment_19_3; }
		
		//Mission
		public RuleCall getMissionsMissionParserRuleCall_19_3_0() { return cMissionsMissionParserRuleCall_19_3_0; }
		
		//("," missions+=Mission)*
		public Group getGroup_19_4() { return cGroup_19_4; }
		
		//","
		public Keyword getCommaKeyword_19_4_0() { return cCommaKeyword_19_4_0; }
		
		//missions+=Mission
		public Assignment getMissionsAssignment_19_4_1() { return cMissionsAssignment_19_4_1; }
		
		//Mission
		public RuleCall getMissionsMissionParserRuleCall_19_4_1_0() { return cMissionsMissionParserRuleCall_19_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19_5() { return cRightCurlyBracketKeyword_19_5; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.Task");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLineTaskParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cShortestPathTaskParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cReturnToStartTaskParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Task:
		//	LineTask | ShortestPathTask | ReturnToStartTask;
		@Override public ParserRule getRule() { return rule; }
		
		//LineTask | ShortestPathTask | ReturnToStartTask
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LineTask
		public RuleCall getLineTaskParserRuleCall_0() { return cLineTaskParserRuleCall_0; }
		
		//ShortestPathTask
		public RuleCall getShortestPathTaskParserRuleCall_1() { return cShortestPathTaskParserRuleCall_1; }
		
		//ReturnToStartTask
		public RuleCall getReturnToStartTaskParserRuleCall_2() { return cReturnToStartTaskParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class AreaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.Area");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAreaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMaxXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXmaxAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXmaxEIntParserRuleCall_4_0 = (RuleCall)cXmaxAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cMaxYKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cYmaxAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cYmaxEIntParserRuleCall_8_0 = (RuleCall)cYmaxAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Area:
		//	{Area}
		//	'('
		//	'max x' '=' xmax=EInt
		//	','
		//	'max y' '=' ymax=EInt
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//{Area} '(' 'max x' '=' xmax=EInt ',' 'max y' '=' ymax=EInt ')'
		public Group getGroup() { return cGroup; }
		
		//{Area}
		public Action getAreaAction_0() { return cAreaAction_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//'max x'
		public Keyword getMaxXKeyword_2() { return cMaxXKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//xmax=EInt
		public Assignment getXmaxAssignment_4() { return cXmaxAssignment_4; }
		
		//EInt
		public RuleCall getXmaxEIntParserRuleCall_4_0() { return cXmaxEIntParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//'max y'
		public Keyword getMaxYKeyword_6() { return cMaxYKeyword_6; }
		
		//'='
		public Keyword getEqualsSignKeyword_7() { return cEqualsSignKeyword_7; }
		
		//ymax=EInt
		public Assignment getYmaxAssignment_8() { return cYmaxAssignment_8; }
		
		//EInt
		public RuleCall getYmaxEIntParserRuleCall_8_0() { return cYmaxEIntParserRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class WaypointTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.WaypointType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWaypointTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//WaypointType:
		//	{WaypointType} name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{WaypointType} name=EString
		public Group getGroup() { return cGroup; }
		
		//{WaypointType}
		public Action getWaypointTypeAction_0() { return cWaypointTypeAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class WayPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.WayPoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWaypointtypesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cWaypointtypesWaypointTypeCrossReference_0_0 = (CrossReference)cWaypointtypesAssignment_0.eContents().get(0);
		private final RuleCall cWaypointtypesWaypointTypeEStringParserRuleCall_0_0_1 = (RuleCall)cWaypointtypesWaypointTypeCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAmpersandKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cWaypointtypesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cWaypointtypesWaypointTypeCrossReference_1_1_0 = (CrossReference)cWaypointtypesAssignment_1_1.eContents().get(0);
		private final RuleCall cWaypointtypesWaypointTypeEStringParserRuleCall_1_1_0_1 = (RuleCall)cWaypointtypesWaypointTypeCrossReference_1_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cXKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCoord_xAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCoord_xEIntParserRuleCall_6_0 = (RuleCall)cCoord_xAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cYKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCoord_yAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCoord_yEIntParserRuleCall_10_0 = (RuleCall)cCoord_yAssignment_10.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//WayPoint:
		//	waypointtypes+=[WaypointType|EString] ("&" waypointtypes+=[WaypointType|EString])*
		//	name=EString
		//	'('
		//	'x' '=' coord_x=EInt
		//	','
		//	'y' '=' coord_y=EInt
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//waypointtypes+=[WaypointType|EString] ("&" waypointtypes+=[WaypointType|EString])* name=EString '(' 'x' '=' coord_x=EInt
		//',' 'y' '=' coord_y=EInt ')'
		public Group getGroup() { return cGroup; }
		
		//waypointtypes+=[WaypointType|EString]
		public Assignment getWaypointtypesAssignment_0() { return cWaypointtypesAssignment_0; }
		
		//[WaypointType|EString]
		public CrossReference getWaypointtypesWaypointTypeCrossReference_0_0() { return cWaypointtypesWaypointTypeCrossReference_0_0; }
		
		//EString
		public RuleCall getWaypointtypesWaypointTypeEStringParserRuleCall_0_0_1() { return cWaypointtypesWaypointTypeEStringParserRuleCall_0_0_1; }
		
		//("&" waypointtypes+=[WaypointType|EString])*
		public Group getGroup_1() { return cGroup_1; }
		
		//"&"
		public Keyword getAmpersandKeyword_1_0() { return cAmpersandKeyword_1_0; }
		
		//waypointtypes+=[WaypointType|EString]
		public Assignment getWaypointtypesAssignment_1_1() { return cWaypointtypesAssignment_1_1; }
		
		//[WaypointType|EString]
		public CrossReference getWaypointtypesWaypointTypeCrossReference_1_1_0() { return cWaypointtypesWaypointTypeCrossReference_1_1_0; }
		
		//EString
		public RuleCall getWaypointtypesWaypointTypeEStringParserRuleCall_1_1_0_1() { return cWaypointtypesWaypointTypeEStringParserRuleCall_1_1_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//'x'
		public Keyword getXKeyword_4() { return cXKeyword_4; }
		
		//'='
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }
		
		//coord_x=EInt
		public Assignment getCoord_xAssignment_6() { return cCoord_xAssignment_6; }
		
		//EInt
		public RuleCall getCoord_xEIntParserRuleCall_6_0() { return cCoord_xEIntParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'y'
		public Keyword getYKeyword_8() { return cYKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//coord_y=EInt
		public Assignment getCoord_yAssignment_10() { return cCoord_yAssignment_10; }
		
		//EInt
		public RuleCall getCoord_yEIntParserRuleCall_10_0() { return cCoord_yEIntParserRuleCall_10_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11() { return cRightParenthesisKeyword_11; }
	}
	public class MissionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.Mission");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTaskAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTaskTaskParserRuleCall_2_0 = (RuleCall)cTaskAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTaskAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTaskTaskParserRuleCall_3_1_0 = (RuleCall)cTaskAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Mission:
		//	name=EString
		//	'{'
		//	task+=Task ("," task+=Task)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString '{' task+=Task ("," task+=Task)* '}'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//task+=Task
		public Assignment getTaskAssignment_2() { return cTaskAssignment_2; }
		
		//Task
		public RuleCall getTaskTaskParserRuleCall_2_0() { return cTaskTaskParserRuleCall_2_0; }
		
		//("," task+=Task)*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//task+=Task
		public Assignment getTaskAssignment_3_1() { return cTaskAssignment_3_1; }
		
		//Task
		public RuleCall getTaskTaskParserRuleCall_3_1_0() { return cTaskTaskParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class LineTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.LineTask");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWaypointsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cWaypointsWayPointCrossReference_2_0 = (CrossReference)cWaypointsAssignment_2.eContents().get(0);
		private final RuleCall cWaypointsWayPointEStringParserRuleCall_2_0_1 = (RuleCall)cWaypointsWayPointCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cWaypointsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cWaypointsWayPointCrossReference_3_1_0 = (CrossReference)cWaypointsAssignment_3_1.eContents().get(0);
		private final RuleCall cWaypointsWayPointEStringParserRuleCall_3_1_0_1 = (RuleCall)cWaypointsWayPointCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//LineTask:
		//	'line'
		//	'('
		//	waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])*
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'line' '(' waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])* ')'
		public Group getGroup() { return cGroup; }
		
		//'line'
		public Keyword getLineKeyword_0() { return cLineKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//waypoints+=[WayPoint|EString]
		public Assignment getWaypointsAssignment_2() { return cWaypointsAssignment_2; }
		
		//[WayPoint|EString]
		public CrossReference getWaypointsWayPointCrossReference_2_0() { return cWaypointsWayPointCrossReference_2_0; }
		
		//EString
		public RuleCall getWaypointsWayPointEStringParserRuleCall_2_0_1() { return cWaypointsWayPointEStringParserRuleCall_2_0_1; }
		
		//("," waypoints+=[WayPoint|EString])*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//waypoints+=[WayPoint|EString]
		public Assignment getWaypointsAssignment_3_1() { return cWaypointsAssignment_3_1; }
		
		//[WayPoint|EString]
		public CrossReference getWaypointsWayPointCrossReference_3_1_0() { return cWaypointsWayPointCrossReference_3_1_0; }
		
		//EString
		public RuleCall getWaypointsWayPointEStringParserRuleCall_3_1_0_1() { return cWaypointsWayPointEStringParserRuleCall_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ShortestPathTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.ShortestPathTask");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cShortestPathKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWaypointsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cWaypointsWayPointCrossReference_2_0 = (CrossReference)cWaypointsAssignment_2.eContents().get(0);
		private final RuleCall cWaypointsWayPointEStringParserRuleCall_2_0_1 = (RuleCall)cWaypointsWayPointCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cWaypointsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cWaypointsWayPointCrossReference_3_1_0 = (CrossReference)cWaypointsAssignment_3_1.eContents().get(0);
		private final RuleCall cWaypointsWayPointEStringParserRuleCall_3_1_0_1 = (RuleCall)cWaypointsWayPointCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ShortestPathTask:
		//	'shortest path'
		//	'('
		//	waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])*
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'shortest path' '(' waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])* ')'
		public Group getGroup() { return cGroup; }
		
		//'shortest path'
		public Keyword getShortestPathKeyword_0() { return cShortestPathKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//waypoints+=[WayPoint|EString]
		public Assignment getWaypointsAssignment_2() { return cWaypointsAssignment_2; }
		
		//[WayPoint|EString]
		public CrossReference getWaypointsWayPointCrossReference_2_0() { return cWaypointsWayPointCrossReference_2_0; }
		
		//EString
		public RuleCall getWaypointsWayPointEStringParserRuleCall_2_0_1() { return cWaypointsWayPointEStringParserRuleCall_2_0_1; }
		
		//("," waypoints+=[WayPoint|EString])*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//waypoints+=[WayPoint|EString]
		public Assignment getWaypointsAssignment_3_1() { return cWaypointsAssignment_3_1; }
		
		//[WayPoint|EString]
		public CrossReference getWaypointsWayPointCrossReference_3_1_0() { return cWaypointsWayPointCrossReference_3_1_0; }
		
		//EString
		public RuleCall getWaypointsWayPointEStringParserRuleCall_3_1_0_1() { return cWaypointsWayPointEStringParserRuleCall_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ReturnToStartTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "se.jam.turtlebot.MyDsl.ReturnToStartTask");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReturnToStartTaskAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReturnToStartKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ReturnToStartTask:
		//	{ReturnToStartTask}
		//	'return to start';
		@Override public ParserRule getRule() { return rule; }
		
		//{ReturnToStartTask} 'return to start'
		public Group getGroup() { return cGroup; }
		
		//{ReturnToStartTask}
		public Action getReturnToStartTaskAction_0() { return cReturnToStartTaskAction_0; }
		
		//'return to start'
		public Keyword getReturnToStartKeyword_1() { return cReturnToStartKeyword_1; }
	}
	
	
	private final TurtleBotElements pTurtleBot;
	private final TaskElements pTask;
	private final EStringElements pEString;
	private final AreaElements pArea;
	private final WaypointTypeElements pWaypointType;
	private final WayPointElements pWayPoint;
	private final MissionElements pMission;
	private final EIntElements pEInt;
	private final LineTaskElements pLineTask;
	private final ShortestPathTaskElements pShortestPathTask;
	private final ReturnToStartTaskElements pReturnToStartTask;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTurtleBot = new TurtleBotElements();
		this.pTask = new TaskElements();
		this.pEString = new EStringElements();
		this.pArea = new AreaElements();
		this.pWaypointType = new WaypointTypeElements();
		this.pWayPoint = new WayPointElements();
		this.pMission = new MissionElements();
		this.pEInt = new EIntElements();
		this.pLineTask = new LineTaskElements();
		this.pShortestPathTask = new ShortestPathTaskElements();
		this.pReturnToStartTask = new ReturnToStartTaskElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("se.jam.turtlebot.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TurtleBot:
	//	'TurtleBot'
	//	name=EString
	//	'{' ('area' '=' area=Area)? 'waypoint types' '=' '{' waypointtypes+=WaypointType ("," waypointtypes+=WaypointType)*
	//	'}'
	//	'waypoints' '=' '{' waypoints+=WayPoint ("," waypoints+=WayPoint)* '}'
	//	'bot starts at' '=' bot_start=[WayPoint|EString] ('missions' '=' '{' missions+=Mission ("," missions+=Mission)* '}')?
	//	'}';
	public TurtleBotElements getTurtleBotAccess() {
		return pTurtleBot;
	}
	
	public ParserRule getTurtleBotRule() {
		return getTurtleBotAccess().getRule();
	}
	
	//Task:
	//	LineTask | ShortestPathTask | ReturnToStartTask;
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Area:
	//	{Area}
	//	'('
	//	'max x' '=' xmax=EInt
	//	','
	//	'max y' '=' ymax=EInt
	//	')';
	public AreaElements getAreaAccess() {
		return pArea;
	}
	
	public ParserRule getAreaRule() {
		return getAreaAccess().getRule();
	}
	
	//WaypointType:
	//	{WaypointType} name=EString;
	public WaypointTypeElements getWaypointTypeAccess() {
		return pWaypointType;
	}
	
	public ParserRule getWaypointTypeRule() {
		return getWaypointTypeAccess().getRule();
	}
	
	//WayPoint:
	//	waypointtypes+=[WaypointType|EString] ("&" waypointtypes+=[WaypointType|EString])*
	//	name=EString
	//	'('
	//	'x' '=' coord_x=EInt
	//	','
	//	'y' '=' coord_y=EInt
	//	')';
	public WayPointElements getWayPointAccess() {
		return pWayPoint;
	}
	
	public ParserRule getWayPointRule() {
		return getWayPointAccess().getRule();
	}
	
	//Mission:
	//	name=EString
	//	'{'
	//	task+=Task ("," task+=Task)*
	//	'}';
	public MissionElements getMissionAccess() {
		return pMission;
	}
	
	public ParserRule getMissionRule() {
		return getMissionAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//LineTask:
	//	'line'
	//	'('
	//	waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])*
	//	')';
	public LineTaskElements getLineTaskAccess() {
		return pLineTask;
	}
	
	public ParserRule getLineTaskRule() {
		return getLineTaskAccess().getRule();
	}
	
	//ShortestPathTask:
	//	'shortest path'
	//	'('
	//	waypoints+=[WayPoint|EString] ("," waypoints+=[WayPoint|EString])*
	//	')';
	public ShortestPathTaskElements getShortestPathTaskAccess() {
		return pShortestPathTask;
	}
	
	public ParserRule getShortestPathTaskRule() {
		return getShortestPathTaskAccess().getRule();
	}
	
	//ReturnToStartTask:
	//	{ReturnToStartTask}
	//	'return to start';
	public ReturnToStartTaskElements getReturnToStartTaskAccess() {
		return pReturnToStartTask;
	}
	
	public ParserRule getReturnToStartTaskRule() {
		return getReturnToStartTaskAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
