/*
 * generated by Xtext 2.10.0
 */
package se.chalmers.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import se.chalmers.parser.antlr.internal.InternalTurtleBotMissionDSLParser;
import se.chalmers.services.TurtleBotMissionDSLGrammarAccess;

public class TurtleBotMissionDSLParser extends AbstractAntlrParser {

	@Inject
	private TurtleBotMissionDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTurtleBotMissionDSLParser createParser(XtextTokenStream stream) {
		return new InternalTurtleBotMissionDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TurtleBot";
	}

	public TurtleBotMissionDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TurtleBotMissionDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
