/*
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
