/*
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import se.jam.turtlebot.ide.contentassist.antlr.internal.InternalMyDslParser;
import se.jam.turtlebot.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTaskAccess().getAlternatives(), "rule__Task__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTurtleBotAccess().getGroup(), "rule__TurtleBot__Group__0");
					put(grammarAccess.getTurtleBotAccess().getGroup_3(), "rule__TurtleBot__Group_3__0");
					put(grammarAccess.getTurtleBotAccess().getGroup_8(), "rule__TurtleBot__Group_8__0");
					put(grammarAccess.getTurtleBotAccess().getGroup_14(), "rule__TurtleBot__Group_14__0");
					put(grammarAccess.getTurtleBotAccess().getGroup_19(), "rule__TurtleBot__Group_19__0");
					put(grammarAccess.getTurtleBotAccess().getGroup_19_4(), "rule__TurtleBot__Group_19_4__0");
					put(grammarAccess.getAreaAccess().getGroup(), "rule__Area__Group__0");
					put(grammarAccess.getWaypointTypeAccess().getGroup(), "rule__WaypointType__Group__0");
					put(grammarAccess.getWayPointAccess().getGroup(), "rule__WayPoint__Group__0");
					put(grammarAccess.getWayPointAccess().getGroup_1(), "rule__WayPoint__Group_1__0");
					put(grammarAccess.getMissionAccess().getGroup(), "rule__Mission__Group__0");
					put(grammarAccess.getMissionAccess().getGroup_3(), "rule__Mission__Group_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getLineTaskAccess().getGroup(), "rule__LineTask__Group__0");
					put(grammarAccess.getLineTaskAccess().getGroup_3(), "rule__LineTask__Group_3__0");
					put(grammarAccess.getShortestPathTaskAccess().getGroup(), "rule__ShortestPathTask__Group__0");
					put(grammarAccess.getShortestPathTaskAccess().getGroup_3(), "rule__ShortestPathTask__Group_3__0");
					put(grammarAccess.getReturnToStartTaskAccess().getGroup(), "rule__ReturnToStartTask__Group__0");
					put(grammarAccess.getTurtleBotAccess().getNameAssignment_1(), "rule__TurtleBot__NameAssignment_1");
					put(grammarAccess.getTurtleBotAccess().getAreaAssignment_3_2(), "rule__TurtleBot__AreaAssignment_3_2");
					put(grammarAccess.getTurtleBotAccess().getWaypointtypesAssignment_7(), "rule__TurtleBot__WaypointtypesAssignment_7");
					put(grammarAccess.getTurtleBotAccess().getWaypointtypesAssignment_8_1(), "rule__TurtleBot__WaypointtypesAssignment_8_1");
					put(grammarAccess.getTurtleBotAccess().getWaypointsAssignment_13(), "rule__TurtleBot__WaypointsAssignment_13");
					put(grammarAccess.getTurtleBotAccess().getWaypointsAssignment_14_1(), "rule__TurtleBot__WaypointsAssignment_14_1");
					put(grammarAccess.getTurtleBotAccess().getBot_startAssignment_18(), "rule__TurtleBot__Bot_startAssignment_18");
					put(grammarAccess.getTurtleBotAccess().getMissionsAssignment_19_3(), "rule__TurtleBot__MissionsAssignment_19_3");
					put(grammarAccess.getTurtleBotAccess().getMissionsAssignment_19_4_1(), "rule__TurtleBot__MissionsAssignment_19_4_1");
					put(grammarAccess.getAreaAccess().getXmaxAssignment_4(), "rule__Area__XmaxAssignment_4");
					put(grammarAccess.getAreaAccess().getYmaxAssignment_8(), "rule__Area__YmaxAssignment_8");
					put(grammarAccess.getWaypointTypeAccess().getNameAssignment_1(), "rule__WaypointType__NameAssignment_1");
					put(grammarAccess.getWayPointAccess().getWaypointtypesAssignment_0(), "rule__WayPoint__WaypointtypesAssignment_0");
					put(grammarAccess.getWayPointAccess().getWaypointtypesAssignment_1_1(), "rule__WayPoint__WaypointtypesAssignment_1_1");
					put(grammarAccess.getWayPointAccess().getNameAssignment_2(), "rule__WayPoint__NameAssignment_2");
					put(grammarAccess.getWayPointAccess().getCoord_xAssignment_6(), "rule__WayPoint__Coord_xAssignment_6");
					put(grammarAccess.getWayPointAccess().getCoord_yAssignment_10(), "rule__WayPoint__Coord_yAssignment_10");
					put(grammarAccess.getMissionAccess().getNameAssignment_0(), "rule__Mission__NameAssignment_0");
					put(grammarAccess.getMissionAccess().getTaskAssignment_2(), "rule__Mission__TaskAssignment_2");
					put(grammarAccess.getMissionAccess().getTaskAssignment_3_1(), "rule__Mission__TaskAssignment_3_1");
					put(grammarAccess.getLineTaskAccess().getWaypointsAssignment_2(), "rule__LineTask__WaypointsAssignment_2");
					put(grammarAccess.getLineTaskAccess().getWaypointsAssignment_3_1(), "rule__LineTask__WaypointsAssignment_3_1");
					put(grammarAccess.getShortestPathTaskAccess().getWaypointsAssignment_2(), "rule__ShortestPathTask__WaypointsAssignment_2");
					put(grammarAccess.getShortestPathTaskAccess().getWaypointsAssignment_3_1(), "rule__ShortestPathTask__WaypointsAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMyDslParser typedParser = (InternalMyDslParser) parser;
			typedParser.entryRuleTurtleBot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
