/*
 * generated by Xtext 2.10.0
 */
package se.jam.turtlebot.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import se.jam.turtlebot.ui.internal.TurtlebotActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TurtlebotActivator.getInstance().getInjector("se.jam.turtlebot.MyDsl");
	}

}
